### ISSUE TITLE
Release on PyPi

### ISSUE THREAD

**Issue by alerque** [alif-type/sfd2ufo#10]
I noticed in #9 you don't have plans to bake this into `fontmake`. Do you have plans to develop it at all? What about releasing to PyPi*?

I'm using this in several places and have a vested interest in keeping the windows from breaking. If you don't plan on running with it I might be interested in at least keeping it afloat.

\* <sub>Note I already extracted [`sfdnormalize`](https://github.com/alerque/sfdnormalize) from its former home burried in Libertinus sources (including history from its even earlier homes) and am keeping it around and [published on PyPi](https://pypi.org/project/sfdnormalize/).<sub>

**Comment by khaledhosny** [comment]
> I noticed in #9 you don't have plans to bake this into `fontmake`. Do you have plans to develop it at all? What about releasing to PyPi*?

I don’t think I’m ready for commiting to a stable API/behavior. I have been using it for personal projects and developing it as I go, but I don’t know if it is generally usable in its current form. One major change that I’d like to do first is to parse to some sort of objects that better reflect SFD structure, so one can build a font/manipulate it without going through UFO first. UFO conversation can be then rewritten on top of it.

> * Note I already extracted [`sfdnormalize`](https://github.com/alerque/sfdnormalize) from its former home burried in Libertinus sources (including history from its even earlier homes) and am keeping it around and [published on PyPi](https://pypi.org/project/sfdnormalize/).

`sfdnormslize` was inside Libertinus repository because it was never supposed to be a general tool (even its original form was DejaVu specific) and it does questionable things that are only acceptable because of how Libertinus is maintained and built.

**Comment by bkmgit** [comment]
Adding this to PyPi would be very helpful. It is a dependency of [fontship](https://github.com/theleagueof/fontship).

**Comment by ctrlcctrlv** [comment]
As I just released `sfdutf7` on PyPI, I could do the same for this if that's what's decided in #13 (which has become more about this than my original constrained suggestion).

**Comment by ctrlcctrlv** [comment]
I am re-targeting this issue to be only about `PyPi`, if other problems with my future plans exist they can be opened separately :-)

**Comment by ctrlcctrlv** [comment]
https://pypi.org/project/sfdLib/
